name: Test Access Token

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --local user.email "test@example.com"
          git config --local user.name "Test User"
          git checkout -b test-branch

      - name: Add a file
        run: |
          echo "Test file content" > test-file.txt
          git add test-file.txt
          git commit -m "Add test file"

      - name: Push changes
        run: |
          set -x  # Enable debugging
          git push origin test-branch
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
